### ISSUE TITLE
OpenAPI, AsyncAPIの作成

### ISSUE THREAD

**Issue by Riku-0801** [CODEDUEL2022/CODE_DUEL_Final#69]

**Comment by yutteee** [comment]
Socket.ioをAsyncAPIを使ってドキュメント化するハンズオン
https://www.asyncapi.com/blog/socketio-part1

**Comment by yutteee** [comment]
asyncAPI、socket.ioをちゃんとサポートしているわけではなさそう。
> AsyncAPI currently does not support Socket.IO binding and Web Socket like syntax used for now.

openAPIみたいに、クライアント、サーバー側で自動で型生成するライブラリが整っているわけでもないので、使わない方が良い気がしてきた...

https://www.asyncapi.com/blog/socketio-automatic-docs

**Comment by yutteee** [comment]
API定義メモ

- スタート画面: 特になし
- ホーム画面
  - deck一覧画面
    - deck一覧を取得する関数
    - `/deck`
- ゲーム画面
  - カードドロー
    - `/draw`
  - カード一覧
    - `/card`
  - カード詳細
    - `/card/id`
